# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				dolphin = true
				chicken = true
				item = true
				salmon = true
				zombie_villager = true
				chest_minecart = true
				pig = true
				pillager = true
				skeleton = true
				area_effect_cloud = true
				bat = true
				zombie = true
				cod = true
				glow_squid = true
				witch = true
				glow_item_frame = false
				squid = true
				drowned = true
				spider = true
				sheep = true
				creeper = true
				player = true
				enderman = true

			[light_sources.settings.entities.automobility]
				automobile = true

			[light_sources.settings.entities.mythicmobs]
				mushroom_thing = true
				drake = true
				chupacabra = true

