# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# Enable block entities light source.
	block_entities = true
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				glow_item_frame = false
				player = true
				skeleton = true
				turtle = true
				sheep = true
				area_effect_cloud = true
				dolphin = true
				squid = true
				pufferfish = true
				cod = true
				tropical_fish = true
				zombie = true
				bat = true
				creeper = true
				spider = true
				item = true
				enderman = true

			[light_sources.settings.entities.naturalist]
				coral_snake = true
				vulture = true

			[light_sources.settings.entities.promenade]
				sunken_skeleton = true
				lush_creeper = true

			[light_sources.settings.entities.mca]
				female_zombie_villager = true

			[light_sources.settings.entities.rottencreatures]
				undead_miner = true

